### PR TITLE
Adding in border and adding .gitignore to bin/

### PR DESCRIPTION
**Pull request by Fogest**
I have added in a border that is adjusted based on whatever your terminal size is. 

I also removed the `.empty` file and switched it to a `.gitignore` file and made it ignore the `output` file. I know you had a `make clean` to avoid commiting the output file in the commit however I think this is a better solution to avoid people inexperienced with git from accidentally commiting the file without the clean.

Ref issue #4

### CODE REVIEW

**Comment by Fogest** [comment]
Don't pull this yet, removing the modifying readme file commit. Was making a demo video of this procedure.

**Comment by Fogest** [comment]
I have added a video to the readme file that I made. Feel free to not include this commit if you do not want the video in the readme file.

**Comment by jstncarvalho** [comment]
Looks good. But since it was sent to master, I'm going to wait till next week's lecture before merging it. In case anyone else wants to work on issues, or just grab the lecture code.

**Comment by Fogest** [comment]
Resubmitted pull request to development branch.

**Pull request closed without merging**
